version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: openexchangerates
      POSTGRES_USER: spribe
      POSTGRES_PASSWORD: the_best
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  spribe-task:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/openexchangerates
      SPRING_DATASOURCE_USERNAME: spribe
      SPRING_DATASOURCE_PASSWORD: the_best

volumes:
  postgres_data: